[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
; monitor_filters = esp32_exception_decoder

lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/DHT sensor library @ ^1.4.6
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.9.0
    https://github.com/WifWaf/MH-Z19.git
    https://github.com/adafruit/Adafruit_VL53L0X.git
    links2004/WebSockets @ ^2.4.1

build_flags = 
    -Os
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_ESP_TASK_WDT_INIT=1
    -DCONFIG_ESP_TASK_WDT_TIMEOUT_S=5
